<a href="https://colab.research.google.com/github/cyh716/CYH716.github.io/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [8]:
# Import torch
import torch

# Create random tensor
tensor1=torch.rand(7,7)
print(tensor1)

tensor([[0.2442, 0.0792, 0.0603, 0.7150, 0.0712, 0.6043, 0.2119],
        [0.3987, 0.1375, 0.7767, 0.1546, 0.9720, 0.1141, 0.8486],
        [0.4441, 0.1623, 0.0152, 0.1311, 0.0444, 0.4688, 0.0033],
        [0.8535, 0.6391, 0.1032, 0.3262, 0.8904, 0.3240, 0.0591],
        [0.6340, 0.0497, 0.1468, 0.5553, 0.2012, 0.4650, 0.6467],
        [0.6914, 0.3039, 0.0823, 0.1949, 0.7082, 0.3694, 0.7644],
        [0.7791, 0.0112, 0.5156, 0.5610, 0.5362, 0.2483, 0.4122]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
tensor2=torch.rand(1,7).T
# Perform matrix multiplication
tensor=tensor1 @ tensor2
print(tensor,tensor.shape)

tensor([[1.0384],
        [1.7820],
        [0.7856],
        [2.3313],
        [1.4233],
        [1.8806],
        [1.7372]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
torch.manual_seed(23)
# Create two random tensors
tensor1=torch.rand(7,7)
tensor2=torch.rand(1,7).T
# Matrix multiply tensors
tensor=tensor1 @ tensor2
print(tensor,tensor.shape)

tensor([[1.7550],
        [1.9489],
        [1.5575],
        [1.9645],
        [2.0376],
        [1.9741],
        [1.3910]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)  # Sets seed for GPU operations


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.cuda.manual_seed(1234)
# Check for access to GPU
device="cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
tensor1=torch.rand(2,3).to(device)
tensor2=torch.rand(2,3).to(device)
print(f"Device: {device}")
print(f"{tensor1},{tensor1.device}\n{tensor2},{tensor2.device}")

Device: cpu
tensor([[0.6524, 0.7804, 0.0450],
        [0.4816, 0.8964, 0.9583]]),cpu
tensor([[0.7729, 0.7437, 0.6313],
        [0.1613, 0.5894, 0.3005]]),cpu



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
tensor = tensor1 @ tensor2.T
print(tensor,tensor.shape)

tensor([[1.1130, 0.5787],
        [1.6439, 0.8940]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(tensor.max())
# Find min
print(tensor.min())

tensor(1.6439)
tensor(0.5787)


### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
max_idx=tensor.argmax()
max_i,max_j=max_idx//2,max_idx%2
print(f"index of maximum value:({max_i},{max_j})")
# Find arg min
min_idx=tensor.argmin()
min_i,min_j=min_idx//2,min_idx%2
print(f"index of minimum value:({min_i},{min_j})")

index of maximum value:(1,0)
index of minimum value:(0,1)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [29]:
# Set seed
torch.manual_seed(7)
# Create random tensor
tensor=torch.rand(1,1,1,10)
# Remove single dimensions
tensor_squeezed=tensor.squeeze()
# Print out tensors and their shapes
print(tensor,tensor.shape)
print(tensor_squeezed,tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
